name: Debug Secrets

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  debug:
    runs-on: ubuntu-latest
    name: Debug Secret Configuration
    environment: production  # Use production environment secrets
    steps:
      - name: Check Secrets Exist
        run: |
          echo "Checking if secrets are configured..."
          echo "===================================="
          
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "❌ VERCEL_TOKEN is NOT set"
          else
            echo "✅ VERCEL_TOKEN is set"
            echo "Token starts with: ${VERCEL_TOKEN:0:4}..."
            echo "Token length: ${#VERCEL_TOKEN}"
          fi
          
          if [ -z "${{ secrets.VERCEL_ORG_ID }}" ]; then
            echo "❌ VERCEL_ORG_ID is NOT set"
          else
            echo "✅ VERCEL_ORG_ID is set: ${{ secrets.VERCEL_ORG_ID }}"
          fi
          
          if [ -z "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "❌ VERCEL_PROJECT_ID is NOT set"
          else
            echo "✅ VERCEL_PROJECT_ID is set"
            echo "Project ID: ${VERCEL_PROJECT_ID:0:8}..."
          fi
          
          echo "===================================="
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          
      - name: Test Vercel CLI with Token
        if: ${{ secrets.VERCEL_TOKEN != '' }}
        run: |
          npm i -g vercel
          echo "Testing Vercel authentication..."
          vercel whoami --token="${{ secrets.VERCEL_TOKEN }}" || echo "Token authentication failed"
